### PR TITLE
Test python 3.9

### PR DESCRIPTION
**Pull request by romainmartinez**

### CODE REVIEW

**Comment by romainmartinez** [comment]
As stated in [this post](https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying), the error came from the `xlsx` reader implemented in `pandas` and Python 3.9.

I'll wait a bit to see if the developers fix the error.
A workaround is to install another engine (`openpyxl`) to read the excel file:
```python
pd.read_excel('data.xlsx', engine='openpyxl')
```

**Comment by pariterre** [comment]
Ok! Ping me when you are ready for review! :)

**Comment by romainmartinez** [comment]
@pariterre This is ready to be merged

**Review by pariterre — APPROVED** [review]
LGTM

**Pull request merged**
