### PR TITLE
Update installation instructions

### PR DESCRIPTION
**Pull request by romainmartinez**
## Proposed changes

Update installation instruction because PYOMECA IS ON CONDA-FORGE :tada: 

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by pariterre** [comment]
Woot!

**Comment by romainmartinez** [comment]
@pariterre, you can merge :+1:

**Comment by pariterre** [comment]
Should we update the README so it conforms to PR Quality Review?

**Comment by romainmartinez** [comment]
I will do it in a future PR

**Pull request merged**
