### PR TITLE
fix _vectors methods bug

### PR DESCRIPTION
**Pull request by romainmartinez**
## Proposed changes

The `_to_vectors` function, which is called every time a file is opened, contained a bug:
for example, if a data file contains the channels `["Voltage.1", "Voltage.1_Biceps"]` and you want to get `"Voltage.1"`, the function returned ``Voltage.1_Biceps`` because ``Voltage.1`` is included in ``Voltage.1_Biceps``.

The new version is cleaner and avoids this bug

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by pariterre** [comment]
Not sure if it was not actually intended... 
the tests don't pass anymore... If the user doesn't know exactly the name of the analog, that makes it harder to use... But maybe it is his own problem! 
Do you know why one test fails?

**Comment by romainmartinez** [comment]
We can't leave it like that because in case there are two channel names that start the same way, the user has no way to get the channel with the shortest name.
Vicon often introduces prefixes, so this case has often happened on my data.

Anyway, if the user does not know the channel names, he just has to call the read function without `names` and `idx` to return all the data

I haven't had time to see why the test doesn't work, I'll check it out soon :)

**Comment by pariterre** [comment]
Should I approve this PR?

**Comment by pariterre** [comment]
Hi @romainmartinez !
If you repair the one broken test, we could finally terminate this PR haha!

**Comment by romainmartinez** [comment]
Yep, I will do it in the next few days :+1:

**Comment by romainmartinez** [comment]
Alright tests passed !

It was a prefix issue in the c3d file.

If we take the example of querying 'EMG1' in a c3d file containing the `'Delt_ant.EMG1'` channel.

This will works with the old code snippet because `EMG1` "is in" `'Delt_ant.EMG1'` but it is wrong: 

```python
    @classmethod
    def _to_vectors(cls, data, idx, all_names, target_names, metadata=None):
        if not idx:
            # find names in column_names
            idx = []
            for i, m in enumerate(target_names):
                idx.append([i for i, s in enumerate(all_names) if m in s][0])
```

With the new version, the exact channels are pulled.

**Pull request merged**
